//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearchWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SavedJob
    {
        public int SJobId { get; set; }

        [Display(Name = "Job ID")]
        public int JobsId { get; set; }
        public int UserId { get; set; }
    

        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
